---
# Install Apache and PHP5 modules

 - name: Install apache2
   apt: name=apache2 state=present

 - name: Install php5
   apt: name=php5 state=present

 - name: Install php5-mysql
   apt: name=php5-mysql state=present

 - name: Install php5-gd
   apt: name=php5-gd state=present
  
   notify: restart apache

 - name: apache state
   service: name=apache2 state=started enabled=yes

# Install iptables-persistent
# - name: Install iptables-persistent
#   apt: name=iptables-persistent state=present
